### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [iqbalfhrzii/Project1#1]
### Halo Iqbal

Kode struktur kurang tepat, bisa diperbaiki mengikuti contoh struktur dibawah yah:
```html
<header>...</header>
<main>
 <div id="content">
  <section id="article">
   <article id="">...</article>
   ...
  </section>
  <section id="form">...</section>
  ...
 </div>
 <aside>...</aside>
</main>
<footer>...</footer>
```
Lalu, `nav` bisa dipindah dari `main` kedalam `header. Untuk `form` bisa dipindah dari `footer` kedalam `section`nya sendiri pada `div id="content"`

Yang lain udah oke, bisa direvisi lalu upload ulang di repository ini juga, lalu komen dibawah jika sudah upload ulang ya. Terimakasih

**Comment by iqbalfhrzii** [comment]
Baik kak, terimakasih sudah memberi masukannya. ini sudah saya revisi dan mohon di cek kembali 
Iqbal Fahrozi - 11221034 - https://github.com/iqbalfhrzii/Project1

**Comment by not-xygen** [comment]
### Hi Iqbal

Kode struktur sedikit lagi bener, hanya perlu mengeluarkan `aside` dari `div id="content"`, jadi seperti dibawah ya
```html
<main>
 <div id="content">...</div>
 <aside>...</aside>
</main>
```

Tolong diperbaiki ya dan upload kembali, lalu untuk submissionnya ku approve langsung dan Goodluck di CSS nanti!

**Comment by iqbalfhrzii** [comment]
Baik kak, ini sudah saya revisi lagi. mohon di cek kembali
Iqbal Fahrozi - 11221034 - https://github.com/iqbalfhrzii/Project1

**Comment by not-xygen** [comment]
Oke sudah kuapprove ya, Goodluck pada saat belajar CSS
